[package]
name = "wasm-dev-book-hello-wasm"
version = "0.1.0"
authors = ["gonzaemon111 <goki14914@icloud.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
